version: "3.7"

services:
  redis:
    image: redis
    expose:
      - 6379
    networks:
      - task-manager-network

  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - task-manager-network
  db:
    image: mysql:8.0
    environment:
       MYSQL_DB: task_manager
       MYSQL_ROOT_PASSWORD: task_manager
    networks:
      - task-manager-network
    volumes:
      - db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - "4000"
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started

    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - task-manager-network
    volumes:
      - ./src:/app/src
    environment:
        DB_USER: root
        DB_PASS: task_manager
        DB_NAME: task_manager
        DB_HOST: db
        REDIS_URL: redis://redis
        AMQP_URL: amqp://guest:guest@rabbitmq:5672

volumes:
  db:

networks:
  task-manager-network: {}
