version: "3.7"

services:
  db:
    image: mysql:8.0
    environment:
       MYSQL_DB: task_manager
       MYSQL_ROOT_PASSWORD: task_manager
    networks:
      - task-manager-network
    volumes:
      - db:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    expose:
      - "4000"
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      db:
        condition: service_started
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - task-manager-network
    environment:
        DB_USER: root
        DB_PASS: task_manager
        DB_NAME: task_manager
        DB_HOST: db

volumes:
  db:

networks:
  task-manager-network: {}
